### ISSUE TITLE
ImportError: cannot import name upath

### ISSUE THREAD

**Issue by balwinder132** [teddziuba/django-sslserver#16]
Hello ,
I am using django 1.4 , but this django ssl server doesn't seem to work here it gives Error 'ImportError: cannot import name upath' i guess upath is not present in my django.utils._os . Do i need to use some specific version of django ssl server for django 1.4 ? Please Help in this matter.

Thanks

**Comment by daspacebar** [comment]
![Screenshot 2021-06-24 at 9 50 05 AM](https://user-images.githubusercontent.com/58136275/123202067-8fc15e80-d4d1-11eb-9707-8500eb3da2b3.png)
This is a upgradation process from djang1.11 to django3.2, and I've removed all the new versions and have installed all the latest ones along with djang3.2, but when running the project, `upath` error pops up. Any clue? The #1 doesn't fix it.
