### ISSUE TITLE
proper command line syntax with certificates

### ISSUE THREAD

**Issue by retbrook-2** [teddziuba/django-sslserver#25]
How do I run the manage.py command with an ip address and port with the certificates?

from the documentation the command line is
$ python manage.py runsslserver --certificate /path/to/certificate.crt --key /path/to/key.key

so where do I put 127.0.0.1:8020 , after the certificates???

$ python manage.py runsslserver --certificate /path/to/certificate.crt --key /path/to/key.key 127.0.0.1:8020

And should the leading slash be placed where it is, or should I not put it there so that Linux is using the relative path?

Thanks

**Comment by jsetting32** [comment]
I'd like to know this as well : /

**Comment by battlemidget** [comment]
Run with `--addrport 127.0.0.1:8080`

**Comment by battlemidget** [comment]
Feel free to file a PR for the readme otherwise I can do it tomorrow

**Comment by abhivemp** [comment]
Hi, I am trying this right now and the command seems unrecognized

```
$ python manage.py runsslserver --certificate cert.crt --key key.key --addrport 192.168.1.2:8000
```
And I get

```
usage: manage.py runsslserver [-h] [--ipv6] [--nothreading] [--noreload]
                              [--certificate CERTIFICATE] [--key KEY]
                              [--nostatic] [--static] [--version]
                              [-v {0,1,2,3}] [--settings SETTINGS]
                              [--pythonpath PYTHONPATH] [--traceback]
                              [--no-color] [--force-color]
                              [addrport]
manage.py runsslserver: error: unrecognized arguments: --addrport
```

Am I missing something @adam-stokes
