### ISSUE TITLE
What django version is supported?

### ISSUE THREAD

**Issue by cabello** [teddziuba/django-sslserver#28]
Hi,

On `requirements.txt` I see the project is enforcing version `1.4`, does it work on version `1.6` or `1.7` as well?

Thanks,

**Comment by ankitml** [comment]
I am having problems after migrating Django to 1.7. The issue is with static files, sometimes they stop loading without any error or warning. Is this happening to anyone else?

**Comment by edmenendez** [comment]
Based on the syntax of the runsslserver django command I don't think this is compatible with Django versions before 1.8. It's using the new (not backward compatible) syntax.

**Comment by cabello** [comment]
We upgraded our Django version and I am currently using Django 1.8, but still not sure if the latest stable version is supported by this project.

**Comment by battlemidget** [comment]
@cabello yea it supports 1.8

**Comment by battlemidget** [comment]
Fixed in master

**Comment by cabello** [comment]
Thanks :)
