### ISSUE TITLE
Documentation: clarify use of other static file handlers

### ISSUE THREAD

**Issue by boydjj** [teddziuba/django-sslserver#33]
With #21, the default behavior if `staticfiles` is installed is to use `django.contrib.staticfiles.handlers.StaticFilesHandler`. This can cause unexpected 404s -- e.g., when using `runsslserver` in conjunction with WhiteNoise. The documentation should clarify that in these cases it makes sense to include the `--nostatic` flag. Happy to submit a PR if it would be useful.

**Comment by battlemidget** [comment]
@boydjj please do that'll help move this along

Thanks!
