### ISSUE TITLE
Chrome is phasing out acceptance of the SHA1 hashing algorithm for key signatures

### ISSUE THREAD

**Issue by aljp** [teddziuba/django-sslserver#35]
Hi

So I'm using django-sslserver to run my local dev on https://localhost:8000, I'm having some issues with chrome complaining about the certificate.

I've added exceptions for the certificate in chrome, but it still complains due to the use of SHA-1 it seems 
![django-sslserver-problem](https://cloud.githubusercontent.com/assets/1378224/7763581/68cdd77a-0086-11e5-8f9d-7a4a23c7b67a.png)

Should I roll out another certificate using a different hashing algorithm as a fix for the time being and replace the old one?  Also should a different algorithm be used by django-sslserver in the future?  

Some relevant links http://security.stackexchange.com/a/52838 and http://googleonlinesecurity.blogspot.com.au/2014/09/gradually-sunsetting-sha-1.html which indicate google is phasing out acceptance of SHA-1

**Comment by johnthagen** [comment]
The bundled certificate should updated to use a SHA256 signature.

**Comment by johnthagen** [comment]
@battlemidget would you accept a PR for a new development certificate, or would you prefer to create that yourself?

**Comment by battlemidget** [comment]
For development that would be good if you wanted to create that PR
