### ISSUE TITLE
No auto-reload support

### ISSUE THREAD

**Issue by jmg** [teddziuba/django-sslserver#38]
It would be great to add auto-reload to the runsslserver command. Like the runserver functionality.

**Comment by rmoorman** [comment]
As far as I can tell, auto-reload is not working on django > 1.7. I have a project using 1.7 where auto-reload is working fine.

I just started a new project using 1.8 and can confirm that it does not work there.

@jmg are you working with django 1.8 too?

**Comment by battlemidget** [comment]
Patches definitely welcomed as I'm short on free time to work on this

Thanks!

**Comment by jmg** [comment]
@rmoorman yeah, django 1.8 caused me the no auto-reload issue. I'll try to submit a patch for this.

**Comment by Tusky** [comment]
Yeah, it's not working with Django 1.8.6 either. :(

**Comment by battlemidget** [comment]
I just merged a commit which should address this, can you guys please test? If all goes well I'll push out a new release to pypi

**Comment by Tusky** [comment]
works for me :+1:

**Comment by rmoorman** [comment]
works over here too :+1:

**Comment by battlemidget** [comment]
Thanks ill get a package pushed out today

**Comment by battlemidget** [comment]
Uploaded to pypi, thanks all

**Comment by jmg** [comment]
Finally got the time to test it. Upgraded it directly from pip and worked! Thanks all!
