### ISSUE TITLE
Update pypi package

### ISSUE THREAD

**Issue by elky** [teddziuba/django-sslserver#47]
Can you please update pypi package with this change? https://github.com/teddziuba/django-sslserver/commit/722082197e072e01eb1a856674ab887ea399e821

**Comment by elky** [comment]
Oh wait, it doesn't work with Python 2.6 and deprecated in 2.7.13. Seems there should be python version checking.

**Comment by johnthagen** [comment]
Tested the change on Python 3.6.2 and it works. Would be nice to have a new release on PyPI for this.

If it breaks older versions of Python, they can target the 0.19 release.

**Comment by johnthagen** [comment]
For more info, see the [`ssl.PROTOCOL_TLSv1_2`](https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_TLSv1_2) docs.

> New in version 2.7.9.
> Deprecated since version 2.7.13: OpenSSL has deprecated all version specific protocols. Use the default protocol with flags like `OP_NO_SSLv3` instead.

So anyway, the current master branch ready to go to PyPI will work for 2.7.9+, which seems reasonable for a Django SSL testing library. Django itself doesn't even support 2.6 anymore.

**Comment by battlemidget** [comment]
I'll try to get this done tonight or tomorrow

**Comment by johnthagen** [comment]
@battlemidget I think everything that I wanted to help fix has been merged now, so looking forward to the next PyPI release. Thanks.

**Comment by battlemidget** [comment]
Thanks Ill get this done tomorrow am

**Comment by battlemidget** [comment]
0.20 released
