### ISSUE TITLE
Do not recommend runserver for production

### ISSUE THREAD

**Issue by rfleschenberg** [teddziuba/django-sslserver#50]
Hi,

Using runserver in production is officially "forbidden": https://docs.djangoproject.com/en/1.11/ref/django-admin/#runserver

Right now, the README somewhat encourages to use django-sslserver in production (in the section about browser certificate errors). Can we add a warning to the README that people should not use this in production, or at the very least be aware of the risks and limitations?

**Comment by battlemidget** [comment]
Can you propose a PR so we can review? Thanks!
