### ISSUE TITLE
Document which Python versions are supported

### ISSUE THREAD

**Issue by johnthagen** [teddziuba/django-sslserver#54]
It would be helpful to document in setup.py which versions of Python are explicitly supported. Nowadays it's pretty typical to support 2.7, 3.4+ or just 3.4+ (I haven't tested this on 2.7).

This is typically done with [trove classifiers](https://pypi.python.org/pypi?%3Aaction=list_classifiers).

If you let me know what versions you plan to support, I'm happy to submit a PR for it.

**Comment by johnthagen** [comment]
Should also put the Django version as a trove classifier.

**Comment by battlemidget** [comment]
PR's welcomed!

**Comment by johnthagen** [comment]
@battlemidget what would the supported versions be?
