### ISSUE TITLE
Add Travis CI build

### ISSUE THREAD

**Issue by johnthagen** [teddziuba/django-sslserver#59]
It would help give better confidence which Python versions the project works on if there was some automated CI builds. I'm happy to create one, but https://travis-ci.org/teddziuba/django-sslserver needs to be activated first. @battlemidget are you able to do that?

**Comment by battlemidget** [comment]
I'll check and see

**Comment by battlemidget** [comment]
Looks like I don't have sufficient access, I'll email Ted and see if I can get that enabled

**Comment by battlemidget** [comment]
@teddziuba is it possible to get us connected to travis-ci?

**Comment by johnthagen** [comment]
Reference CI configuration from another Django plugin project:

- https://github.com/beda-software/drf-writable-nested/blob/master/.travis.yml
- https://github.com/beda-software/drf-writable-nested/blob/master/tox.ini

**Comment by johnthagen** [comment]
[Travis CI (.com) is no longer free for FOSS projects](https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing) so closing this issue.
