### ISSUE TITLE
django.utils._os.upath no longer exists in Django 3.0

### ISSUE THREAD

**Issue by Penspinner** [teddziuba/django-sslserver#92]
https://github.com/teddziuba/django-sslserver/blob/master/sslserver/management/commands/runsslserver.py#L7

`django.utils._os.upath` has been removed from Django 3.0.
https://docs.djangoproject.com/en/3.0/releases/3.0/#removed-private-python-2-compatibility-apis

Is there a way around this?

**Comment by mathiasbalslow** [comment]
Have the same issue

**Comment by peledies** [comment]
Same here

**Comment by peledies** [comment]
I have created a pull request https://github.com/teddziuba/django-sslserver/pull/94 that fixes this issue.

**Comment by penspinner** [comment]
Closing as this has been fixed with https://github.com/teddziuba/django-sslserver/pull/94 and released in version `django-sslserver==0.22`.
